"""Build the raw-VA dispatch table from the REAL generated guest_table.c and
prove, on the host, that every translated function resolves and every
non-member misses (recomp/runtime/guest_dispatch_table_oracle.c).

The generated table is not part of the repository.  Pass --table, set
ISAAC_GUEST_TABLE, or rely on the default candidates below."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

import build_all as BA


HERE = Path(__file__).resolve().parent
RUNTIME = HERE / "runtime"
VITA_CMAKE = HERE / "vita" / "CMakeLists.txt"
IMAGE_SIZE = 0x00840000
PASS_PREFIX = "guest dispatch table oracle: PASS ("


def default_candidates() -> list[Path]:
    # build_vita.py writes the generated corpus to ../repentogxm-build/vita-generated
    # by default; ISAAC_GUEST_TABLE or --table override this.
    return [
        HERE / "generated" / "guest_table.c",
        HERE.parent.parent / "repentogxm-build" / "vita-generated" / "guest_table.c",
    ]


def locate_table(explicit: str | None) -> Path | None:
    if explicit:
        path = Path(explicit)
        if not path.is_file():
            raise SystemExit(f"--table {path} does not exist")
        return path
    env = os.environ.get("ISAAC_GUEST_TABLE")
    if env:
        path = Path(env)
        if not path.is_file():
            raise SystemExit(f"ISAAC_GUEST_TABLE={path} does not exist")
        return path
    for candidate in default_candidates():
        if candidate.is_file():
            return candidate
    return None


def parse_table(path: Path) -> tuple[list[int], list[int]]:
    source = path.read_text(encoding="utf-8")
    addrs = re.search(
        r"static const uint32_t s_addrs\[\] = \{(.*?)\};", source, re.DOTALL)
    if addrs is None:
        raise AssertionError("s_addrs[] not found")
    rvas = [int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]+)U", addrs.group(1))]
    registered = re.search(r"guest_register\(s_addrs, s_fns, (\d+)\);", source)
    if registered is None or int(registered.group(1)) != len(rvas):
        raise AssertionError("guest_register count disagrees with s_addrs[]")
    if any(b <= a for a, b in zip(rvas, rvas[1:])):
        raise AssertionError("s_addrs[] is not strictly ascending")
    if rvas and rvas[-1] >= IMAGE_SIZE:
        raise AssertionError("s_addrs[] exceeds the oracle image size")
    imports = re.search(
        r"static const guest_import s_imports\[\] = \{(.*?)\};", source,
        re.DOTALL)
    if imports is None:
        raise AssertionError("s_imports[] not found")
    slots = [int(v, 16) for v in
             re.findall(r"\{\s*0x([0-9a-fA-F]+)U,\s*\"", imports.group(1))]
    import_count = re.search(
        r"guest_register_imports\(s_imports, (\d+)U\);", source)
    if import_count is None or int(import_count.group(1)) != len(slots):
        raise AssertionError("guest_register_imports count disagrees")
    return rvas, slots


def write_keys_header(root: Path, table: Path, rvas: list[int],
                      slots: list[int]) -> Path:
    def rows(values: list[int]) -> str:
        lines = []
        for index in range(0, len(values), 8):
            lines.append("    " + ", ".join(
                f"0x{v:08x}U" for v in values[index:index + 8]) + ",")
        return "\n".join(lines)

    header = root / "guest_dispatch_oracle_keys.h"
    header.write_text(
        "/* GENERATED by test_guest_dispatch_table.py from "
        f"{table.name} */\n"
        f"#define ORACLE_TABLE_NAME \"{table.parent.parent.name}/"
        f"{table.parent.name}/{table.name}\"\n"
        f"#define ORACLE_RVA_COUNT {len(rvas)}U\n"
        "static const uint32_t s_oracle_rvas[ORACLE_RVA_COUNT] = {\n"
        f"{rows(rvas)}\n}};\n"
        f"#define ORACLE_IMPORT_COUNT {len(slots)}U\n"
        "static const uint32_t s_oracle_import_rvas[ORACLE_IMPORT_COUNT] = {\n"
        f"{rows(slots)}\n}};\n",
        encoding="utf-8", newline="\n")
    return header


def verify_cmake_gate() -> None:
    source = VITA_CMAKE.read_text(encoding="utf-8")
    option = re.compile(
        r"option\(ISAAC_VITA_DISPATCH_TABLE\s+\"[^\"]+\"\s+OFF\)", re.DOTALL)
    if option.search(source) is None:
        raise AssertionError("dispatch table is not a default-OFF option")
    # The owner-scope block is the innermost `if(ISAAC_VITA_DISPATCH_TABLE)`
    # around the three-source set_property.  Other seams (mutex, floor
    # thunk) legitimately scope the same define to their own host files in
    # earlier `if(ISAAC_VITA_DISPATCH_TABLE)` blocks, so the span must be
    # anchored at the set_property and widened to the nearest enclosing
    # `if`/`endif`, never taken from the first `if` in the file.
    owner = re.compile(
        r"set_property\(SOURCE\s+"
        r'"\$\{ISAAC_RUNTIME\}/guest\.c"\s+'
        r'"\$\{ISAAC_RUNTIME\}/kage_vita_phase_profile\.c"\s+'
        r'"\$\{ISAAC_RUNTIME\}/host_vita_import_id\.c"\s+'
        r"APPEND PROPERTY COMPILE_DEFINITIONS\s+"
        r"ISAAC_VITA_GUEST_DISPATCH_TABLE=1\)",
        re.DOTALL)
    match = owner.search(source)
    if match is None:
        raise AssertionError("dispatch table is not scoped to guest.c")
    opener = "if(ISAAC_VITA_DISPATCH_TABLE)"
    start = source.rfind(opener, 0, match.start())
    if start < 0:
        raise AssertionError("dispatch table is not scoped to guest.c")
    if "endif()" in source[start:match.start()]:
        raise AssertionError("dispatch table set_property is outside its if()")
    end = source.find("endif()", match.end())
    if end < 0:
        raise AssertionError("dispatch table scope is not closed")
    if "guest_0" in source[start:end]:
        raise AssertionError("dispatch table leaked into generated units")


def run(command: list[str], env: dict[str, str]) -> str:
    completed = subprocess.run(
        command, cwd=HERE, env=env,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output = completed.stdout.decode("cp866", errors="replace")
    if completed.returncode != 0:
        print(output, end="")
        raise subprocess.CalledProcessError(completed.returncode, command)
    return output


LEGS = (
    ("perf", ("/DISAAC_VITA_GUEST_LOOKUP_CACHE=1",
              "/DISAAC_VITA_GUEST_DISPATCH_TABLE=1",
              "/DISAAC_VITA_PHASE_PROFILE=1")),
    ("no-cache", ("/DISAAC_VITA_GUEST_DISPATCH_TABLE=1",
                  "/DISAAC_VITA_PHASE_PROFILE=1")),
    ("no-profile", ("/DISAAC_VITA_GUEST_DISPATCH_TABLE=1",)),
    # wf/opt-gltok: the 73 typed-GL tokens join the REAL table (gl_bridge.c
    # and host_vita_gl.c linked in for the trampolines and the slow block).
    ("gl-tokens", ("/DISAAC_VITA_GUEST_LOOKUP_CACHE=1",
                   "/DISAAC_VITA_GUEST_DISPATCH_TABLE=1",
                   "/DISAAC_VITA_PHASE_PROFILE=1",
                   "/DISAAC_VITA_GL_SHIM_FASTDISPATCH=1",
                   "/DISAAC_VITA_GL_SHIM_TABLE_TOKENS=1")),
)
GL_TOKEN_SOURCES = (RUNTIME / "gl_bridge.c", RUNTIME / "host_vita_gl.c")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--table", help="generated guest_table.c")
    args = parser.parse_args()
    verify_cmake_gate()
    table = locate_table(args.table)
    if table is None:
        print("guest dispatch table oracle: SKIP (no generated guest_table.c; "
              "pass --table or set ISAAC_GUEST_TABLE)")
        return 0
    rvas, slots = parse_table(table)
    expected_prefix = (
        f"{PASS_PREFIX}{table.parent.parent.name}/{table.parent.name}/"
        f"{table.name}: {len(rvas)} VA keys resolve exactly; misses: "
        f"{len(rvas)} RVA-form, {2 * len(slots)} IAT RVA+VA, 2049 tokens, ")
    env, compiler = BA.msvc_env()
    with tempfile.TemporaryDirectory(prefix="isaac-dispatch-table-") as temp:
        root = Path(temp)
        write_keys_header(root, table, rvas, slots)
        for name, definitions in LEGS:
            executable = root / f"dispatch-table-{name}.exe"
            objects = root / f"obj-{name}"
            objects.mkdir()
            sources = [str(RUNTIME / "guest_dispatch_table_oracle.c")]
            if "/DISAAC_VITA_GL_SHIM_TABLE_TOKENS=1" in definitions:
                sources += [str(path) for path in GL_TOKEN_SOURCES]
            run([
                compiler, "/nologo", "/W4", "/WX", "/O2", "/Gy", "/std:c11",
                "/wd4310", "/wd4702", "/wd4996",
                "/DGUEST_IMAGE_BASE=0x98000000u", *definitions,
                "/I", str(RUNTIME), "/I", str(root),
                *sources,
                "/Fe:" + str(executable),
                "/Fo:" + str(objects) + os.sep,
                "/link", "/OPT:REF", "/INCREMENTAL:NO",
            ], env)
            output = run([str(executable)], env)
            pass_line = [line for line in output.splitlines()
                         if line.startswith(PASS_PREFIX)]
            if not pass_line or not pass_line[0].startswith(expected_prefix):
                print(output, end="")
                raise AssertionError(
                    f"dispatch table oracle ({name}) did not pass: "
                    f"expected {expected_prefix!r}")
            boot = [line for line in output.splitlines()
                    if line.startswith("guest: dispatch table ready: "
                                       f"{len(rvas)} keys, 0 skipped")]
            if not boot:
                print(output, end="")
                raise AssertionError(
                    f"dispatch table oracle ({name}) never reported a ready "
                    "table for every key")
            if "/DISAAC_VITA_GL_SHIM_TABLE_TOKENS=1" in definitions:
                tokens = [line for line in output.splitlines()
                          if line.startswith(
                              "guest dispatch table oracle: GL tokens=73 ")]
                # guest_register builds before the flag is up (0 tokens);
                # the import registration and the image window bring 73.
                if not tokens or ", 73 GL tokens, " not in boot[-1] or                         ", 0 GL tokens, " not in boot[0]:
                    print(output, end="")
                    raise AssertionError(
                        f"dispatch table oracle ({name}) did not place the "
                        "73 typed-GL tokens")
                print(f"[{name}] {tokens[0]}")
            elif "GL tokens" in boot[0]:
                raise AssertionError(
                    f"dispatch table oracle ({name}) reports GL tokens "
                    "without the option")
            print(f"[{name}] {boot[-1]}")
            print(f"[{name}] {pass_line[0]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
