/* Keep oracle native aliases out of guest_gl_backend member access. */
#undef glActiveTexture
#undef glAlphaFunc
#undef glAttachShader
#undef glBindFramebuffer
#undef glBindRenderbuffer
#undef glBindTexture
#undef glBlendFuncSeparate
#undef glBlitNamedFramebuffer
#undef glCheckFramebufferStatus
#undef glCheckNamedFramebufferStatus
#undef glClear
#undef glClearColor
#undef glClearDepth
#undef glColorMask
#undef glCompileShader
#undef glCreateProgram
#undef glCreateShader
#undef glCullFace
#undef glDeleteFramebuffers
#undef glDeleteProgram
#undef glDeleteRenderbuffers
#undef glDeleteShader
#undef glDeleteTextures
#undef glDepthFunc
#undef glDisable
#undef glDisableVertexAttribArray
#undef glDrawElements
#undef glEnable
#undef glEnableVertexAttribArray
#undef glFinish
#undef glFramebufferRenderbuffer
#undef glFramebufferTexture2D
#undef glGenFramebuffers
#undef glGenRenderbuffers
#undef glGenTextures
#undef glGetAttribLocation
#undef glGetBooleanv
#undef glGetError
#undef glGetFloatv
#undef glGetIntegerv
#undef glGetProgramInfoLog
#undef glGetProgramiv
#undef glGetShaderInfoLog
#undef glGetShaderiv
#undef glGetString
#undef glGetStringi
#undef glGetUniformLocation
#undef glIsEnabled
#undef glLinkProgram
#undef glReadPixels
#undef glRenderbufferStorage
#undef glShaderSource
#undef glTexImage2D
#undef glTexParameteri
#undef glTexSubImage2D
#undef glUniform1fv
#undef glUniform1i
#undef glUniform1iv
#undef glUniform2fv
#undef glUniform2iv
#undef glUniform3fv
#undef glUniform3iv
#undef glUniform4fv
#undef glUniform4iv
#undef glUniformMatrix2fv
#undef glUniformMatrix3fv
#undef glUniformMatrix4fv
#undef glUseProgram
#undef glVertexAttribPointer
#undef glViewport
