/* Actual Vita wrapper, with host-only stream/kernel boundaries. This checks
 * observation removal, not the independently tested decoder/real guest libpng.
 * Build as a 32-bit host executable; no source extraction or rewritten owner. */
#include <errno.h>
#include <setjmp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../../runtime/host_vita_native_png.c"

_Static_assert(sizeof(uintptr_t) == 4, "the wrapper has 32-bit guest pointers");

enum { TELL = 1, SEEK = 2, READ = 3 };
enum {
    NORMAL, CHUNKED, SHORT_READ, BAD_CRC, BAD_SHAPE, TELL_STACK,
    SEEK_STACK, ALLOC_REFUSED, REWIND_FAILED, READ_LONGJMP,
    REAL_LONGJMP, ROW_NULL, CASE_COUNT
};
static const char *const case_names[CASE_COUNT] = {
    "normal", "chunked", "short-read", "bad-crc", "bad-shape", "tell-stack",
    "seek-stack", "alloc-refused", "rewind-failed", "read-longjmp",
    "real-longjmp", "row-null"
};
/* zlib.compress(b''.join(bytes([0])+bytes(range(1+y*12,13+y*12))
 *                         for y in range(3)), 0), produced by Python zlib. */
static const uint8_t compressed[50] = {
    0x78,0x01,0x01,0x27,0x00,0xd8,0xff,0x00,0x01,0x02,0x03,0x04,0x05,
    0x06,0x07,0x08,0x09,0x0a,0x0b,0x0c,0x00,0x0d,0x0e,0x0f,0x10,0x11,
    0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x00,0x19,0x1a,0x1b,0x1c,0x1d,
    0x1e,0x1f,0x20,0x21,0x22,0x23,0x24,0x22,0x95,0x02,0x9b
};
static uint32_t arena[4096], scratch_words[16384];
static CPU cpu;
static uint8_t stream_data[128];
static uint32_t stream_size, stream_pos, first_remaining;
static unsigned scenario, calls[4], clock_calls, logs, rewinds, real_calls;
static unsigned allocs, frees, faulted, trace_hash;
static uint32_t read_arg_slot, read_arg_value;
static jmp_buf escape;

#define CHECK(x) do { if (!(x)) { \
    fprintf(stderr, "CHECK failed: %s:%d: %s\n", __FILE__, __LINE__, #x); \
    exit(2); } } while (0)

static uint32_t ptr(const void *p) { return (uint32_t)(uintptr_t)p; }
static uint32_t png_ptr(void) { return ptr(arena); }
static uint32_t row_ptr(void) { return ptr(arena + 256); }
static uint32_t stream_ptr(void) { return ptr(arena + 512); }

static uint32_t hash_word(uint32_t hash, uint32_t word)
{
    unsigned i;
    for (i = 0; i < 4; ++i) {
        hash = (hash ^ (word & 255U)) * 16777619U;
        word >>= 8;
    }
    return hash;
}

static uint32_t hash_memory(uint32_t hash, const void *memory, size_t size)
{
    const uint8_t *p = memory;
    while (size >= 4U) {
        uint32_t value;
        memcpy(&value, p, 4U);
        hash = hash_word(hash, value);
        p += 4U;
        size -= 4U;
    }
    while (size--) hash = (hash ^ *p++) * 16777619U;
    return hash;
}

uint64_t sceKernelGetProcessTimeWide(void)
{
    ++clock_calls;
    return 1000000U + (uint64_t)clock_calls * 11U;
}

void isaac_vita_log(const char *format, ...)
{
    ++logs;
    if (strstr(format, "REWIND FAILED")) ++rewinds;
}

SceUID sceKernelAllocMemBlock(const char *name, int type, SceSize bytes,
                            const void *options)
{
    (void)name; (void)options;
    CHECK(type == SCE_KERNEL_MEMBLOCK_TYPE_USER_RW);
    ++allocs;
    if (scenario == ALLOC_REFUSED || bytes > sizeof scratch_words) return -1;
    return 7;
}
int sceKernelGetMemBlockBase(SceUID uid, void **out)
{
    CHECK(uid == 7);
    *out = scratch_words;
    return 0;
}
int sceKernelFreeMemBlock(SceUID uid)
{
    CHECK(uid == 7);
    ++frees;
    return 0;
}

void guest_fault(CPU *__restrict c, uint32_t addr, const char *what)
{
    c->fault = what;
    c->fault_addr = addr;
    ++faulted;
    longjmp(escape, 1);
}
int guest_stack_violation(CPU *__restrict c, uint32_t pc, uint32_t kind,
                         uint32_t addr, uint32_t size)
{
    (void)kind; (void)size;
    guest_fault(c, addr, "fixture stack violation");
    return (int)pc;
}
int guest_stack_owner_violation(CPU *__restrict c, uint32_t pc)
{
    guest_fault(c, pc, "fixture stack owner");
    return 0;
}

/* Regenerated by the runner from the current, unmodified guest.c helpers. */
#include "native-png-clock-stack.inc"

void guest_call(CPU *__restrict c, uint32_t target)
{
    uint32_t sp = c->esp;
    CHECK(c->ecx == stream_ptr());
    CHECK(target >= TELL && target <= READ);
    CHECK(ld32(sp) == ISAAC_NP_SITE_STREAM_READ_RVA);
    ++calls[target];
    trace_hash = hash_word(trace_hash, target);
    trace_hash = hash_word(trace_hash, stream_pos);
    if (target == TELL) {
        c->eax = stream_pos;
        if (scenario == TELL_STACK && calls[TELL] == 1) return;
        c->esp += 4;
    } else if (target == SEEK) {
        uint32_t pos = ld32(sp + 4);
        CHECK(ld32(sp + 8) == 0);
        trace_hash = hash_word(trace_hash, pos);
        if ((scenario == SEEK_STACK && calls[SEEK] == 1) ||
            (scenario == REWIND_FAILED && calls[SEEK] == 2)) return;
        CHECK(pos <= stream_size);
        stream_pos = pos;
        c->eax = 0;
        c->esp += 12;
    } else {
        uint32_t dst = ld32(sp + 4), n = ld32(sp + 12), got;
        CHECK(ld32(sp + 8) == 1);
        read_arg_slot = sp + 4;
        read_arg_value = dst;
        if (scenario == READ_LONGJMP)
            guest_fault(c, stream_pos, "fixture nonlocal read");
        CHECK(stream_pos <= stream_size);
        got = stream_size - stream_pos;
        if (got > n) got = n;
        memcpy((void *)(uintptr_t)dst, stream_data + stream_pos, got);
        stream_pos += got;
        c->eax = got;
        c->esp += 16;
        trace_hash = hash_word(trace_hash, n);
        trace_hash = hash_word(trace_hash, got);
    }
}

/* Deliberately simple translated-row boundary: the real decoder is covered
 * by its existing oracle, not reimplemented here. Exercise return/state and
 * nonlocal-exit behavior of the actual native wrapper around that boundary. */
void __real_sub_005b1500(CPU *__restrict c)
{
    uint32_t png = c->ecx, row = c->edx, rn, i;
    ++real_calls;
    if (scenario == REAL_LONGJMP)
        guest_fault(c, png, "fixture nonlocal translated row");
    CHECK(png == png_ptr());
    rn = ld32(png + ISAAC_NP_PNG_ROW_NUMBER);
    CHECK(rn < 3);
    if (row)
        for (i = 0; i < 12; ++i) st8(row + i, (uint8_t)(rn * 12 + i + 1));
    st32(png + ISAAC_NP_PNG_ROW_NUMBER, rn + 1);
#if defined(ISAAC_VITA_NATIVE_PNG_VERIFY)
    if (s_ses.mode == NP_MODE_VERIFY && rn == 2) {
        np_write_final_state(&s_ses);
        stream_pos = s_ses.end_pos;
    }
#endif
    (void)gpop(c);
}

static void be32(uint8_t *p, uint32_t value)
{
    p[0] = (uint8_t)(value >> 24); p[1] = (uint8_t)(value >> 16);
    p[2] = (uint8_t)(value >> 8); p[3] = (uint8_t)value;
}

static void reset(unsigned which)
{
    uint32_t png = png_ptr(), stream = stream_ptr(), vtable = ptr(arena + 528);
    unsigned i;
    scenario = which;
    memset(arena, 0xa5, sizeof arena);
    memset(arena, 0, 0x200);
    memset(scratch_words, 0xa5, sizeof scratch_words);
    memset(&cpu, 0, sizeof cpu);
    memset(&s_ses, 0, sizeof s_ses);
    memset(&s_stats, 0, sizeof s_stats);
    memset(&s_scratch, 0, sizeof s_scratch);
    memset(&s_reserve, 0, sizeof s_reserve);
    memset(s_staging, 0, sizeof s_staging);
    memset(s_last_row, 0, sizeof s_last_row);
    memset(s_tinfl_state, 0xa5, sizeof s_tinfl_state);
    s_init_logged = 0;
    memset(calls, 0, sizeof calls);
    clock_calls = logs = rewinds = real_calls = allocs = frees = faulted = 0;
    read_arg_slot = read_arg_value = 0;
    trace_hash = 2166136261U;
    stream_pos = 0;
    memcpy(stream_data, compressed, sizeof compressed);
    stream_size = first_remaining = sizeof compressed;
    if (which == CHUNKED || which == BAD_CRC) {
        uint32_t crc = isaac_np_crc32(0, "IDAT", 4);
        first_remaining = 7;
        crc = isaac_np_crc32(crc, compressed, first_remaining);
        if (which == BAD_CRC) crc ^= 1;
        be32(stream_data + 7, crc);
        be32(stream_data + 11, sizeof compressed - 7);
        memcpy(stream_data + 15, "IDAT", 4);
        memcpy(stream_data + 19, compressed + 7, sizeof compressed - 7);
        stream_size = sizeof compressed + 12;
    }
    if (which == SHORT_READ || which == REWIND_FAILED) stream_size -= 3;
    for (i = 0; i < 8; ++i) cpu.r[i] = 0x12345600U + i;
    cpu.f_a = 0x09876543; cpu.f_b = 0x01020304; cpu.f_r = 0x0abcdef0;
    cpu.f_op = 3; cpu.f_sz = 32; cpu.f_cf = 1; cpu.df = 1;
    cpu.last_error = 0xdeadbeef;
    cpu.stack_owner = &cpu;
    cpu.stack_floor = ptr(arena + 2048);
    cpu.stack_ceiling = ptr(arena + 4096);
    cpu.stack_low_water = cpu.esp = cpu.stack_ceiling - 64;
    st32(stream, vtable);
    st32(vtable + ISAAC_NP_STREAM_VT_TELL, TELL);
    st32(vtable + ISAAC_NP_STREAM_VT_SEEK, SEEK);
    st32(vtable + ISAAC_NP_STREAM_VT_READ, READ);
    st32(png + ISAAC_NP_PNG_FLAGS, ISAAC_NP_FLAG_ROW_INIT);
    st32(png + ISAAC_NP_PNG_MODE, ISAAC_NP_MODE_HAVE_IDAT);
    st32(png + ISAAC_NP_PNG_WIDTH, 3);
    st32(png + ISAAC_NP_PNG_HEIGHT, 3);
    st32(png + ISAAC_NP_PNG_NUM_ROWS, 3);
    st32(png + ISAAC_NP_PNG_ROWBYTES, 12);
    st32(png + ISAAC_NP_PNG_IROWBYTES, 13);
    st32(png + ISAAC_NP_PNG_IWIDTH, 3);
    st32(png + ISAAC_NP_PNG_ROW_BUF, ptr(arena + 272));
    st32(png + ISAAC_NP_PNG_PREV_ROW, ptr(arena + 280));
    st32(png + ISAAC_NP_PNG_IDAT_SIZE, first_remaining);
    st32(png + ISAAC_NP_PNG_CRC, isaac_np_crc32(0, "IDAT", 4));
    st32(png + ISAAC_NP_PNG_READ_DATA_FN,
         (uint32_t)GUEST_IMAGE_BASE + ISAAC_NP_DEFAULT_READ_FN_RVA);
    st32(png + ISAAC_NP_PNG_IO_PTR, stream);
    st8(png + ISAAC_NP_PNG_BIT_DEPTH, 8);
    st8(png + ISAAC_NP_PNG_COLOR_TYPE, 6);
    st8(png + ISAAC_NP_PNG_CHANNELS, 4);
    st8(png + ISAAC_NP_PNG_PIXEL_DEPTH, 32);
    if (which == BAD_SHAPE || which == REAL_LONGJMP)
        st8(png + ISAAC_NP_PNG_INTERLACED, 1);
}

static void wrapper_case(unsigned which)
{
    uint32_t digest, saved_esp;
    unsigned row, expected_fault;
    CPU snapshot;
    uint32_t memory[4096];
    reset(which);
    saved_esp = cpu.esp;
    errno = EDOM;
    if (setjmp(escape) == 0) {
        for (row = 0; row < 3; ++row) {
            cpu.ecx = png_ptr();
            cpu.edx = which == ROW_NULL ? 0 : row_ptr();
            gpush(&cpu, ISAAC_NP_READ_ROW_SITE_RVA);
            __wrap_sub_005b1500(&cpu);
            CHECK(cpu.esp == saved_esp);
            CHECK(ld32(png_ptr() + ISAAC_NP_PNG_ROW_NUMBER) == row + 1);
        }
    }
    expected_fault = which == READ_LONGJMP || which == REAL_LONGJMP;
    CHECK(faulted == expected_fault);
    CHECK(errno == EDOM);
    CHECK(cpu.last_error == 0xdeadbeef);
    CHECK(cpu.f_a == 0x09876543 && cpu.f_b == 0x01020304 && cpu.f_r == 0x0abcdef0);
    CHECK(cpu.f_op == 3 && cpu.f_sz == 32 && cpu.f_cf == 1 && cpu.df == 1);
    CHECK(rewinds == (which == REWIND_FAILED));
    if (!expected_fault) CHECK(s_ses.active == 0);
    if (!NP_TIMING) CHECK(clock_calls == 0);
    else CHECK(clock_calls > 0);
    /* Rebase only known pointer fields, never integer/pixel words that happen
     * to fall in an ASLR allocation range. Keep all remaining state and bytes,
     * including dead guest-call arguments and stack canaries. */
    memcpy(&snapshot, &cpu, sizeof snapshot);
    snapshot.ecx = cpu.ecx - ptr(arena) + 0x10000000U;
    if (snapshot.edx) snapshot.edx = cpu.edx - ptr(arena) + 0x10000000U;
    snapshot.esp = cpu.esp - ptr(arena) + 0x10000000U;
    snapshot.stack_owner = (CPU *)(uintptr_t)0x40000000U;
    snapshot.stack_floor = cpu.stack_floor - ptr(arena) + 0x10000000U;
    snapshot.stack_ceiling = cpu.stack_ceiling - ptr(arena) + 0x10000000U;
    snapshot.stack_low_water = cpu.stack_low_water - ptr(arena) + 0x10000000U;
    snapshot.fault = cpu.fault ? (const char *)(uintptr_t)1 : NULL;
    if (which == REAL_LONGJMP)
        snapshot.fault_addr = cpu.fault_addr - ptr(arena) + 0x10000000U;
    memcpy(memory, arena, sizeof memory);
#define REBASE_AT(offset) memory[(offset) / 4] = \
    memory[(offset) / 4] - ptr(arena) + 0x10000000U
    REBASE_AT(ISAAC_NP_PNG_IO_PTR);
    REBASE_AT(ISAAC_NP_PNG_ROW_BUF);
    REBASE_AT(ISAAC_NP_PNG_PREV_ROW);
    REBASE_AT(512U * 4U);
    if (memory[ISAAC_NP_PNG_Z_NEXT_OUT / 4]) REBASE_AT(ISAAC_NP_PNG_Z_NEXT_OUT);
#undef REBASE_AT
    if (read_arg_slot && ld32(read_arg_slot) == read_arg_value) {
        uint32_t canonical = 0x50000000U; /* core's private CRC/header array */
        if (read_arg_value >= ptr(s_staging) &&
            read_arg_value - ptr(s_staging) < sizeof s_staging)
            canonical = read_arg_value - ptr(s_staging) + 0x30000000U;
        memory[(read_arg_slot - ptr(arena)) / 4] = canonical;
    }
    digest = hash_memory(2166136261U, &snapshot, sizeof snapshot);
    digest = hash_memory(digest, memory, sizeof memory);
    digest = hash_memory(digest, scratch_words, sizeof scratch_words);
    digest = hash_word(digest, stream_pos);
    digest = hash_word(digest, trace_hash);
    printf("case=%s digest=%08x cpu=%08x memory=%08x scratch=%08x clocks=%u read=%u tell=%u seek=%u real=%u "
           "alloc=%u free=%u logs=%u rewinds=%u fault=%u mode=%u active=%u "
           "images=%u native=%u fallback=%u rows=%u decode_us=%u io_us=%u "
           "serve_us=%u translated_us=%u errno=%d\n",
           case_names[which], digest,
           hash_memory(2166136261U, &snapshot, sizeof snapshot),
           hash_memory(2166136261U, memory, sizeof memory),
           hash_memory(2166136261U, scratch_words, sizeof scratch_words),
           clock_calls, calls[READ], calls[TELL],
           calls[SEEK], real_calls, allocs, frees, logs, rewinds, faulted,
           (unsigned)s_ses.mode, (unsigned)s_ses.active,
           (unsigned)s_stats.images, (unsigned)s_stats.native,
           (unsigned)s_stats.fallbacks, (unsigned)s_stats.rows,
           (unsigned)s_stats.decode_us, (unsigned)s_stats.io_us,
           (unsigned)s_stats.serve_us, (unsigned)s_stats.translated_us, errno);
}

static uint32_t core_read(void *context, uint8_t *dst, uint32_t n)
{
    uint32_t got;
    (void)context;
    ++calls[READ];
    got = stream_size - stream_pos;
    if (got > n) got = n;
    memcpy(dst, stream_data + stream_pos, got);
    stream_pos += got;
    return got;
}

static void core_clock_case(unsigned short_read, unsigned use_clock)
{
    isaac_np_params params;
    isaac_np_work work;
    isaac_np_result result;
    uint8_t raw[39], last[12], staging[17];
    uint32_t state[ISAAC_NP_TINFL_STATE_BYTES / 4];
    reset(short_read ? SHORT_READ : NORMAL);
    memset(&params, 0, sizeof params);
    params.width = params.height = 3;
    params.channels = 4; params.color_type = 6; params.rowbytes = 12;
    params.first_remaining = first_remaining;
    params.crc_entry = isaac_np_crc32(0, "IDAT", 4);
    work.raw = raw; work.staging = staging; work.staging_bytes = sizeof staging;
    work.tinfl_state = state; work.last_row_pre_gamma = last;
    work.now_us = use_clock ? sceKernelGetProcessTimeWide : NULL;
    (void)isaac_np_decode(&params, core_read, NULL, &work, &result);
    CHECK(result.status == (short_read ? ISAAC_NP_REJECT_READ : ISAAC_NP_OK));
    CHECK(clock_calls == (use_clock ? 2 * calls[READ] : 0));
    CHECK(result.io_us == (use_clock ? 11 * calls[READ] : 0));
    printf("core-short=%u callback=%u clocks=%u reads=%u io_us=%u status=%d\n",
           short_read, use_clock, clock_calls, calls[READ],
           (unsigned)result.io_us, result.status);
}

int main(void)
{
    unsigned which, short_read, use_clock;
    for (which = 0; which < CASE_COUNT; ++which) wrapper_case(which);
    for (short_read = 0; short_read < 2; ++short_read)
        for (use_clock = 0; use_clock < 2; ++use_clock)
            core_clock_case(short_read, use_clock);
    return 0;
}
