/* Generated by recomp/gl_surface.py.  Do not edit. */
#ifndef REPENTOGXM_GL_SURFACE_GENERATED_H
#define REPENTOGXM_GL_SURFACE_GENERATED_H

#ifndef REPENTOGXM_GL_BRIDGE_TYPES_READY
#error "include gl_bridge.h, not gl_surface_generated.h directly"
#endif

#define GUEST_GL_SURFACE_COUNT 73u
#define GUEST_GL_ORIGINAL_MEASURED_COUNT 51u
#define GUEST_GL_SUPPLEMENTAL_DIRECT_COUNT 22u
#define GUEST_GL_SURFACE_ABI_SHA256 "98db326f375eb1eef7ea941bd92bcc8f70a91eb3db98ac11683135591d1568ed"
#define GUEST_GL_STATIC_CALL_SITES_LOWER_BOUND 171u
#define GUEST_GL_UNDECODED_CANDIDATE_ROOTS 45u

typedef struct guest_gl_backend {
    void (*glActiveTexture)(guest_gl_enum texture);
    void (*glAlphaFunc)(guest_gl_enum func, guest_gl_float ref);
    void (*glAttachShader)(guest_gl_uint program, guest_gl_uint shader);
    void (*glBindFramebuffer)(guest_gl_enum target, guest_gl_uint framebuffer);
    void (*glBindRenderbuffer)(guest_gl_enum target, guest_gl_uint renderbuffer);
    void (*glBindTexture)(guest_gl_enum target, guest_gl_uint texture);
    void (*glBlendFuncSeparate)(guest_gl_enum sfactorRGB, guest_gl_enum dfactorRGB, guest_gl_enum sfactorAlpha, guest_gl_enum dfactorAlpha);
    guest_gl_enum (*glCheckFramebufferStatus)(guest_gl_enum target);
    void (*glClampColorARB)(guest_gl_enum target, guest_gl_enum clamp);
    void (*glClear)(guest_gl_bitfield mask);
    void (*glClearColor)(guest_gl_float red, guest_gl_float green, guest_gl_float blue, guest_gl_float alpha);
    void (*glClearDepth)(guest_gl_double depth);
    void (*glCompileShader)(guest_gl_uint shader);
    guest_gl_uint (*glCreateProgram)(void);
    guest_gl_uint (*glCreateShader)(guest_gl_enum type);
    void (*glCullFace)(guest_gl_enum mode);
    void (*glDeleteFramebuffers)(guest_gl_sizei n, guest_gl_addr framebuffers);
    void (*glDeleteProgram)(guest_gl_uint program);
    void (*glDeleteRenderbuffers)(guest_gl_sizei n, guest_gl_addr renderbuffers);
    void (*glDeleteShader)(guest_gl_uint shader);
    void (*glDeleteTextures)(guest_gl_sizei n, guest_gl_addr textures);
    void (*glDepthFunc)(guest_gl_enum func);
    void (*glDisableVertexAttribArray)(guest_gl_uint index);
    void (*glDrawElements)(guest_gl_enum mode, guest_gl_sizei count, guest_gl_enum type, guest_gl_addr indices);
    void (*glEnable)(guest_gl_enum cap);
    void (*glEnableVertexAttribArray)(guest_gl_uint index);
    void (*glFramebufferRenderbuffer)(guest_gl_enum target, guest_gl_enum attachment, guest_gl_enum renderbuffertarget, guest_gl_uint renderbuffer);
    void (*glFramebufferTexture2D)(guest_gl_enum target, guest_gl_enum attachment, guest_gl_enum textarget, guest_gl_uint texture, guest_gl_int level);
    void (*glGenFramebuffers)(guest_gl_sizei n, guest_gl_addr framebuffers);
    void (*glGenRenderbuffers)(guest_gl_sizei n, guest_gl_addr renderbuffers);
    void (*glGenTextures)(guest_gl_sizei n, guest_gl_addr textures);
    guest_gl_int (*glGetAttribLocation)(guest_gl_uint program, guest_gl_addr name);
    void (*glGetIntegerv)(guest_gl_enum pname, guest_gl_addr data);
    void (*glGetProgramInfoLog)(guest_gl_uint program, guest_gl_sizei bufSize, guest_gl_addr length, guest_gl_addr infoLog);
    void (*glGetProgramiv)(guest_gl_uint program, guest_gl_enum pname, guest_gl_addr params);
    void (*glGetRenderbufferParameteriv)(guest_gl_enum target, guest_gl_enum pname, guest_gl_addr params);
    void (*glGetShaderInfoLog)(guest_gl_uint shader, guest_gl_sizei bufSize, guest_gl_addr length, guest_gl_addr infoLog);
    void (*glGetShaderiv)(guest_gl_uint shader, guest_gl_enum pname, guest_gl_addr params);
    guest_gl_addr (*glGetString)(guest_gl_enum name);
    guest_gl_addr (*glGetStringi)(guest_gl_enum name, guest_gl_uint index);
    guest_gl_int (*glGetUniformLocation)(guest_gl_uint program, guest_gl_addr name);
    void (*glLinkProgram)(guest_gl_uint program);
    void (*glReadPixels)(guest_gl_int x, guest_gl_int y, guest_gl_sizei width, guest_gl_sizei height, guest_gl_enum format, guest_gl_enum type, guest_gl_addr pixels);
    void (*glRenderbufferStorage)(guest_gl_enum target, guest_gl_enum internalformat, guest_gl_sizei width, guest_gl_sizei height);
    void (*glShaderSource)(guest_gl_uint shader, guest_gl_sizei count, guest_gl_addr string, guest_gl_addr length);
    void (*glTexImage2D)(guest_gl_enum target, guest_gl_int level, guest_gl_int internalformat, guest_gl_sizei width, guest_gl_sizei height, guest_gl_int border, guest_gl_enum format, guest_gl_enum type, guest_gl_addr pixels);
    void (*glTexParameteri)(guest_gl_enum target, guest_gl_enum pname, guest_gl_int param);
    void (*glTexSubImage2D)(guest_gl_enum target, guest_gl_int level, guest_gl_int xoffset, guest_gl_int yoffset, guest_gl_sizei width, guest_gl_sizei height, guest_gl_enum format, guest_gl_enum type, guest_gl_addr pixels);
    void (*glUniform1fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_addr value);
    void (*glUniform1i)(guest_gl_int location, guest_gl_int v0);
    void (*glUniform1iv)(guest_gl_int location, guest_gl_sizei count, guest_gl_addr value);
    void (*glUniform1uiv)(guest_gl_int location, guest_gl_sizei count, guest_gl_addr value);
    void (*glUniform2fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_addr value);
    void (*glUniform2iv)(guest_gl_int location, guest_gl_sizei count, guest_gl_addr value);
    void (*glUniform2uiv)(guest_gl_int location, guest_gl_sizei count, guest_gl_addr value);
    void (*glUniform3fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_addr value);
    void (*glUniform3iv)(guest_gl_int location, guest_gl_sizei count, guest_gl_addr value);
    void (*glUniform3uiv)(guest_gl_int location, guest_gl_sizei count, guest_gl_addr value);
    void (*glUniform4fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_addr value);
    void (*glUniform4iv)(guest_gl_int location, guest_gl_sizei count, guest_gl_addr value);
    void (*glUniform4uiv)(guest_gl_int location, guest_gl_sizei count, guest_gl_addr value);
    void (*glUniformMatrix2fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_boolean transpose, guest_gl_addr value);
    void (*glUniformMatrix2x3fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_boolean transpose, guest_gl_addr value);
    void (*glUniformMatrix2x4fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_boolean transpose, guest_gl_addr value);
    void (*glUniformMatrix3fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_boolean transpose, guest_gl_addr value);
    void (*glUniformMatrix3x2fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_boolean transpose, guest_gl_addr value);
    void (*glUniformMatrix3x4fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_boolean transpose, guest_gl_addr value);
    void (*glUniformMatrix4fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_boolean transpose, guest_gl_addr value);
    void (*glUniformMatrix4x2fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_boolean transpose, guest_gl_addr value);
    void (*glUniformMatrix4x3fv)(guest_gl_int location, guest_gl_sizei count, guest_gl_boolean transpose, guest_gl_addr value);
    void (*glUseProgram)(guest_gl_uint program);
    void (*glVertexAttribPointer)(guest_gl_uint index, guest_gl_int size, guest_gl_enum type, guest_gl_boolean normalized, guest_gl_sizei stride, guest_gl_addr pointer);
    void (*glViewport)(guest_gl_int x, guest_gl_int y, guest_gl_sizei width, guest_gl_sizei height);
} guest_gl_backend;

#endif
