#ifndef ISAAC_HOST_VITA_MATH_H
#define ISAAC_HOST_VITA_MATH_H

#include <stdint.h>

#include "guest.h"

/* Exact contiguous UCRT math import run in the frozen Repentance PE.
 *
 * The range contains 21 four-byte IAT slots, not 22:
 *     (0x60656c - 0x60651c) / 4 + 1 == 21
 * All 21 slots have exact x86 callsite ABI evidence, UCRT value-policy
 * measurements and executable host oracles.  Physical-call totals are static
 * PE sites, not runtime calls. */
#define ISAAC_VITA_MATH_FAMILY_FIRST_IAT_RVA       0x0060651cU
#define ISAAC_VITA_MATH_FAMILY_LAST_IAT_RVA        0x0060656cU
#define ISAAC_VITA_MATH_FAMILY_SLOT_COUNT          21U
#define ISAAC_VITA_MATH_PROVEN_IMPORT_COUNT        21U
#define ISAAC_VITA_MATH_LOUD_IMPORT_COUNT           0U
#define ISAAC_VITA_MATH_PHYSICAL_CALL_COUNT       593U
#define ISAAC_VITA_MATH_PROVEN_PHYSICAL_CALL_COUNT 593U
#define ISAAC_VITA_MATH_LOUD_PHYSICAL_CALL_COUNT    0U

/* Frozen normal-PC coverage reached these five members.  This is a unique
 * import hit set, not a claim that every one of their 511 static sites ran. */
#define ISAAC_VITA_MATH_NORMAL_HIT_IMPORT_COUNT      5U
#define ISAAC_VITA_MATH_NORMAL_HIT_PHYSICAL_CALL_COUNT 511U

#define ISAAC_VITA_MATH_CEIL_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!ceil"
#define ISAAC_VITA_MATH_CEIL_IAT_RVA             0x0060651cU
#define ISAAC_VITA_MATH_CEIL_THUNK_RVA           0x005ec3acU
#define ISAAC_VITA_MATH_CEIL_CALL_COUNT           40U
#define ISAAC_VITA_MATH_CEIL_CALL_FNV64 \
    UINT64_C(0xb7582eedd2206c4c)

#define ISAAC_VITA_MATH_LDEXP_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!ldexp"
#define ISAAC_VITA_MATH_LDEXP_IAT_RVA            0x00606520U
#define ISAAC_VITA_MATH_LDEXP_THUNK_RVA          0x00000000U
#define ISAAC_VITA_MATH_LDEXP_CALL_COUNT           4U
#define ISAAC_VITA_MATH_LDEXP_CALL_FNV64 \
    UINT64_C(0x8066258dea037d64)
#define ISAAC_VITA_MATH_LDEXP_CALL_A_RVA         0x005bbf86U
#define ISAAC_VITA_MATH_LDEXP_RETURN_A_RVA       0x005bbf8cU
#define ISAAC_VITA_MATH_LDEXP_CALL_B_RVA         0x005bbfe5U
#define ISAAC_VITA_MATH_LDEXP_RETURN_B_RVA       0x005bbfebU
#define ISAAC_VITA_MATH_LDEXP_CALL_C_RVA         0x005c81e3U
#define ISAAC_VITA_MATH_LDEXP_RETURN_C_RVA       0x005c81e9U
#define ISAAC_VITA_MATH_LDEXP_CALL_D_RVA         0x005c8224U
#define ISAAC_VITA_MATH_LDEXP_RETURN_D_RVA       0x005c822aU

#define ISAAC_VITA_MATH_FLOOR_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!floor"
#define ISAAC_VITA_MATH_FLOOR_IAT_RVA            0x00606524U
#define ISAAC_VITA_MATH_FLOOR_THUNK_RVA          0x005ec3b2U
#define ISAAC_VITA_MATH_FLOOR_CALL_COUNT         438U
#define ISAAC_VITA_MATH_FLOOR_CALL_FNV64 \
    UINT64_C(0x9bacdc17ac4fe873)

/* First floor site on the statically reconstructed normal path.  This is site
 * evidence, not the current live frontier: a later live run crossed the math
 * family and stopped on heap exhaustion.  The outer wrapper call is included
 * separately from the actual import return PC so an import trace cannot
 * accidentally freeze 0x4af772 as the IAT return. */
#define ISAAC_VITA_MATH_FLOOR_FIRST_WRAPPER_CALL_RVA   0x004af76dU
#define ISAAC_VITA_MATH_FLOOR_FIRST_WRAPPER_RETURN_RVA 0x004af772U
#define ISAAC_VITA_MATH_FLOOR_FIRST_IMPORT_CALL_RVA    0x00047b1dU
#define ISAAC_VITA_MATH_FLOOR_FIRST_IMPORT_RETURN_RVA  0x00047b22U
#define ISAAC_VITA_MATH_FLOOR_DIRECT_CALL_A_RVA        0x004af7e2U
#define ISAAC_VITA_MATH_FLOOR_DIRECT_RETURN_A_RVA      0x004af7e7U
#define ISAAC_VITA_MATH_FLOOR_DIRECT_CALL_B_RVA        0x004af88eU
#define ISAAC_VITA_MATH_FLOOR_DIRECT_RETURN_B_RVA      0x004af893U
#define ISAAC_VITA_MATH_FLOOR_DIRECT_CALL_C_RVA        0x004af8c8U
#define ISAAC_VITA_MATH_FLOOR_DIRECT_RETURN_C_RVA      0x004af8cdU

#define ISAAC_VITA_MATH_COPYSIGNF_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!copysignf"
#define ISAAC_VITA_MATH_COPYSIGNF_IAT_RVA        0x00606528U
#define ISAAC_VITA_MATH_COPYSIGNF_THUNK_RVA      0x00000000U
#define ISAAC_VITA_MATH_COPYSIGNF_CALL_COUNT       1U
#define ISAAC_VITA_MATH_COPYSIGNF_CALL_FNV64 \
    UINT64_C(0xffed4b996bbdc7b0)
#define ISAAC_VITA_MATH_COPYSIGNF_CALL_RVA       0x0002a0e7U
#define ISAAC_VITA_MATH_COPYSIGNF_RETURN_RVA     0x0002a0edU

#define ISAAC_VITA_MATH_FDCLASS_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_fdclass"
#define ISAAC_VITA_MATH_FDCLASS_IAT_RVA          0x0060652cU
#define ISAAC_VITA_MATH_FDCLASS_THUNK_RVA        0x005ec36aU
#define ISAAC_VITA_MATH_FDCLASS_CALL_COUNT         8U
#define ISAAC_VITA_MATH_FDCLASS_CALL_FNV64 \
    UINT64_C(0x585e3d3c1629566c)

#define ISAAC_VITA_MATH_ACOS_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_libm_sse2_acos_precise"
#define ISAAC_VITA_MATH_ACOS_IAT_RVA             0x00606530U
#define ISAAC_VITA_MATH_ACOS_THUNK_RVA           0x005ec370U
#define ISAAC_VITA_MATH_ACOS_CALL_COUNT            1U
#define ISAAC_VITA_MATH_ACOS_CALL_FNV64 \
    UINT64_C(0x3f0d0eff9f1ce351)

#define ISAAC_VITA_MATH_CIFMOD_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_CIfmod"
#define ISAAC_VITA_MATH_CIFMOD_IAT_RVA           0x00606534U
#define ISAAC_VITA_MATH_CIFMOD_THUNK_RVA         0x005ec364U
#define ISAAC_VITA_MATH_CIFMOD_CALL_COUNT          1U
#define ISAAC_VITA_MATH_CIFMOD_CALL_FNV64 \
    UINT64_C(0x2dc77666fec2cefc)

#define ISAAC_VITA_MATH_SQRT_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_libm_sse2_sqrt_precise"
#define ISAAC_VITA_MATH_SQRT_IAT_RVA             0x00606538U
#define ISAAC_VITA_MATH_SQRT_THUNK_RVA           0x005ec3a6U
#define ISAAC_VITA_MATH_SQRT_CALL_COUNT            7U
#define ISAAC_VITA_MATH_SQRT_CALL_FNV64 \
    UINT64_C(0x8a27bd553cc5277a)

#define ISAAC_VITA_MATH_SIN_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_libm_sse2_sin_precise"
#define ISAAC_VITA_MATH_SIN_IAT_RVA              0x0060653cU
#define ISAAC_VITA_MATH_SIN_THUNK_RVA            0x005ec3a0U
#define ISAAC_VITA_MATH_SIN_CALL_COUNT            21U
#define ISAAC_VITA_MATH_SIN_CALL_FNV64 \
    UINT64_C(0x9c6f7ee551cc2b9b)

#define ISAAC_VITA_MATH_POW_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_libm_sse2_pow_precise"
#define ISAAC_VITA_MATH_POW_IAT_RVA              0x00606540U
#define ISAAC_VITA_MATH_POW_THUNK_RVA            0x005ec39aU
#define ISAAC_VITA_MATH_POW_CALL_COUNT            35U
#define ISAAC_VITA_MATH_POW_CALL_FNV64 \
    UINT64_C(0xca49c4f83f78f520)

#define ISAAC_VITA_MATH_ROUNDF_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!roundf"
#define ISAAC_VITA_MATH_ROUNDF_IAT_RVA           0x00606544U
#define ISAAC_VITA_MATH_ROUNDF_THUNK_RVA         0x005ec3b8U
#define ISAAC_VITA_MATH_ROUNDF_CALL_COUNT          2U
#define ISAAC_VITA_MATH_ROUNDF_CALL_FNV64 \
    UINT64_C(0x8e2df9bbace8e986)
#define ISAAC_VITA_MATH_ROUNDF_CALL_A_RVA        0x0003f1e5U
#define ISAAC_VITA_MATH_ROUNDF_RETURN_A_RVA      0x0003f1eaU
#define ISAAC_VITA_MATH_ROUNDF_CALL_B_RVA        0x004b81daU
#define ISAAC_VITA_MATH_ROUNDF_RETURN_B_RVA      0x004b81dfU

#define ISAAC_VITA_MATH_LOG_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_libm_sse2_log_precise"
#define ISAAC_VITA_MATH_LOG_IAT_RVA              0x00606548U
#define ISAAC_VITA_MATH_LOG_THUNK_RVA            0x005ec394U
#define ISAAC_VITA_MATH_LOG_CALL_COUNT             3U
#define ISAAC_VITA_MATH_LOG_CALL_FNV64 \
    UINT64_C(0x236a303c7e881795)

#define ISAAC_VITA_MATH_MODF_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!modf"
#define ISAAC_VITA_MATH_MODF_IAT_RVA             0x0060654cU
#define ISAAC_VITA_MATH_MODF_THUNK_RVA           0x00000000U
#define ISAAC_VITA_MATH_MODF_CALL_COUNT            1U
#define ISAAC_VITA_MATH_MODF_CALL_FNV64 \
    UINT64_C(0xd53b50dbee765909)
#define ISAAC_VITA_MATH_MODF_CALL_RVA            0x0047facdU
#define ISAAC_VITA_MATH_MODF_RETURN_RVA          0x0047fad3U

#define ISAAC_VITA_MATH_NEXTAFTERF_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!nextafterf"
#define ISAAC_VITA_MATH_NEXTAFTERF_IAT_RVA       0x00606550U
#define ISAAC_VITA_MATH_NEXTAFTERF_THUNK_RVA     0x00000000U
#define ISAAC_VITA_MATH_NEXTAFTERF_CALL_COUNT      1U
#define ISAAC_VITA_MATH_NEXTAFTERF_CALL_FNV64 \
    UINT64_C(0x85e1d9c70ed02f6b)
#define ISAAC_VITA_MATH_NEXTAFTERF_CALL_RVA      0x00003c2aU
#define ISAAC_VITA_MATH_NEXTAFTERF_RETURN_RVA    0x00003c30U

#define ISAAC_VITA_MATH_CIATAN2_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_CIatan2"
#define ISAAC_VITA_MATH_CIATAN2_IAT_RVA          0x00606554U
#define ISAAC_VITA_MATH_CIATAN2_THUNK_RVA        0x005ec35eU
#define ISAAC_VITA_MATH_CIATAN2_CALL_COUNT         3U
#define ISAAC_VITA_MATH_CIATAN2_CALL_FNV64 \
    UINT64_C(0xff9c38c9ae56c11d)

#define ISAAC_VITA_MATH_ASIN_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_libm_sse2_asin_precise"
#define ISAAC_VITA_MATH_ASIN_IAT_RVA             0x00606558U
#define ISAAC_VITA_MATH_ASIN_THUNK_RVA           0x005ec376U
#define ISAAC_VITA_MATH_ASIN_CALL_COUNT            1U
#define ISAAC_VITA_MATH_ASIN_CALL_FNV64 \
    UINT64_C(0x9dd0ec24384973e3)

#define ISAAC_VITA_MATH_ATAN_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_libm_sse2_atan_precise"
#define ISAAC_VITA_MATH_ATAN_IAT_RVA             0x0060655cU
#define ISAAC_VITA_MATH_ATAN_THUNK_RVA           0x005ec37cU
#define ISAAC_VITA_MATH_ATAN_CALL_COUNT            5U
#define ISAAC_VITA_MATH_ATAN_CALL_FNV64 \
    UINT64_C(0xe0e20053f3544c50)

#define ISAAC_VITA_MATH_SETUSERMATHERR_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!__setusermatherr"
#define ISAAC_VITA_MATH_SETUSERMATHERR_IAT_RVA   0x00606560U
#define ISAAC_VITA_MATH_SETUSERMATHERR_THUNK_RVA 0x005ec1c4U
#define ISAAC_VITA_MATH_SETUSERMATHERR_CALL_COUNT  1U
#define ISAAC_VITA_MATH_SETUSERMATHERR_CALL_FNV64 \
    UINT64_C(0x1189fb39cadf4f91)
#define ISAAC_VITA_MATH_SETUSERMATHERR_CALL_RVA     0x005eb65cU
#define ISAAC_VITA_MATH_SETUSERMATHERR_RETURN_RVA   0x005eb661U
#define ISAAC_VITA_MATH_SETUSERMATHERR_CALLBACK_RVA 0x00542a20U
#define ISAAC_VITA_MATH_SETUSERMATHERR_CALLBACK_SIZE 3U
#define ISAAC_VITA_MATH_SETUSERMATHERR_CALLBACK_FNV64 \
    UINT64_C(0x58389c18233078ff)

#define ISAAC_VITA_MATH_LOG10_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_libm_sse2_log10_precise"
#define ISAAC_VITA_MATH_LOG10_IAT_RVA            0x00606564U
#define ISAAC_VITA_MATH_LOG10_THUNK_RVA          0x005ec38eU
#define ISAAC_VITA_MATH_LOG10_CALL_COUNT           2U
#define ISAAC_VITA_MATH_LOG10_CALL_FNV64 \
    UINT64_C(0x29f689a9d0314568)

#define ISAAC_VITA_MATH_COS_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_libm_sse2_cos_precise"
#define ISAAC_VITA_MATH_COS_IAT_RVA              0x00606568U
#define ISAAC_VITA_MATH_COS_THUNK_RVA            0x005ec382U
#define ISAAC_VITA_MATH_COS_CALL_COUNT            16U
#define ISAAC_VITA_MATH_COS_CALL_FNV64 \
    UINT64_C(0x72e9ffaa1307cb5c)

#define ISAAC_VITA_MATH_EXP_NAME \
    "api-ms-win-crt-math-l1-1-0.dll!_libm_sse2_exp_precise"
#define ISAAC_VITA_MATH_EXP_IAT_RVA              0x0060656cU
#define ISAAC_VITA_MATH_EXP_THUNK_RVA            0x005ec388U
#define ISAAC_VITA_MATH_EXP_CALL_COUNT             2U
#define ISAAC_VITA_MATH_EXP_CALL_FNV64 \
    UINT64_C(0xdcd4a003887b665e)

/* ID, exact name, IAT RVA, thunk RVA (zero for direct IAT call), complete
 * physical-call count and ordered-RVA FNV-1a.  This list is intentionally in
 * IAT order and covers the whole contiguous family. */
#define ISAAC_VITA_MATH_PROVEN_IMPORTS(X) \
    X(ceil, ISAAC_VITA_MATH_CEIL_NAME, ISAAC_VITA_MATH_CEIL_IAT_RVA, \
      ISAAC_VITA_MATH_CEIL_THUNK_RVA, ISAAC_VITA_MATH_CEIL_CALL_COUNT, \
      ISAAC_VITA_MATH_CEIL_CALL_FNV64) \
    X(ldexp, ISAAC_VITA_MATH_LDEXP_NAME, ISAAC_VITA_MATH_LDEXP_IAT_RVA, \
      ISAAC_VITA_MATH_LDEXP_THUNK_RVA, ISAAC_VITA_MATH_LDEXP_CALL_COUNT, \
      ISAAC_VITA_MATH_LDEXP_CALL_FNV64) \
    X(floor, ISAAC_VITA_MATH_FLOOR_NAME, ISAAC_VITA_MATH_FLOOR_IAT_RVA, \
      ISAAC_VITA_MATH_FLOOR_THUNK_RVA, ISAAC_VITA_MATH_FLOOR_CALL_COUNT, \
      ISAAC_VITA_MATH_FLOOR_CALL_FNV64) \
    X(copysignf, ISAAC_VITA_MATH_COPYSIGNF_NAME, \
      ISAAC_VITA_MATH_COPYSIGNF_IAT_RVA, \
      ISAAC_VITA_MATH_COPYSIGNF_THUNK_RVA, \
      ISAAC_VITA_MATH_COPYSIGNF_CALL_COUNT, \
      ISAAC_VITA_MATH_COPYSIGNF_CALL_FNV64) \
    X(fdclass, ISAAC_VITA_MATH_FDCLASS_NAME, \
      ISAAC_VITA_MATH_FDCLASS_IAT_RVA, ISAAC_VITA_MATH_FDCLASS_THUNK_RVA, \
      ISAAC_VITA_MATH_FDCLASS_CALL_COUNT, ISAAC_VITA_MATH_FDCLASS_CALL_FNV64) \
    X(acos, ISAAC_VITA_MATH_ACOS_NAME, ISAAC_VITA_MATH_ACOS_IAT_RVA, \
      ISAAC_VITA_MATH_ACOS_THUNK_RVA, ISAAC_VITA_MATH_ACOS_CALL_COUNT, \
      ISAAC_VITA_MATH_ACOS_CALL_FNV64) \
    X(cifmod, ISAAC_VITA_MATH_CIFMOD_NAME, ISAAC_VITA_MATH_CIFMOD_IAT_RVA, \
      ISAAC_VITA_MATH_CIFMOD_THUNK_RVA, ISAAC_VITA_MATH_CIFMOD_CALL_COUNT, \
      ISAAC_VITA_MATH_CIFMOD_CALL_FNV64) \
    X(sqrt, ISAAC_VITA_MATH_SQRT_NAME, ISAAC_VITA_MATH_SQRT_IAT_RVA, \
      ISAAC_VITA_MATH_SQRT_THUNK_RVA, ISAAC_VITA_MATH_SQRT_CALL_COUNT, \
      ISAAC_VITA_MATH_SQRT_CALL_FNV64) \
    X(sin, ISAAC_VITA_MATH_SIN_NAME, ISAAC_VITA_MATH_SIN_IAT_RVA, \
      ISAAC_VITA_MATH_SIN_THUNK_RVA, ISAAC_VITA_MATH_SIN_CALL_COUNT, \
      ISAAC_VITA_MATH_SIN_CALL_FNV64) \
    X(pow, ISAAC_VITA_MATH_POW_NAME, ISAAC_VITA_MATH_POW_IAT_RVA, \
      ISAAC_VITA_MATH_POW_THUNK_RVA, ISAAC_VITA_MATH_POW_CALL_COUNT, \
      ISAAC_VITA_MATH_POW_CALL_FNV64) \
    X(roundf, ISAAC_VITA_MATH_ROUNDF_NAME, ISAAC_VITA_MATH_ROUNDF_IAT_RVA, \
      ISAAC_VITA_MATH_ROUNDF_THUNK_RVA, ISAAC_VITA_MATH_ROUNDF_CALL_COUNT, \
      ISAAC_VITA_MATH_ROUNDF_CALL_FNV64) \
    X(log, ISAAC_VITA_MATH_LOG_NAME, ISAAC_VITA_MATH_LOG_IAT_RVA, \
      ISAAC_VITA_MATH_LOG_THUNK_RVA, ISAAC_VITA_MATH_LOG_CALL_COUNT, \
      ISAAC_VITA_MATH_LOG_CALL_FNV64) \
    X(modf, ISAAC_VITA_MATH_MODF_NAME, ISAAC_VITA_MATH_MODF_IAT_RVA, \
      ISAAC_VITA_MATH_MODF_THUNK_RVA, ISAAC_VITA_MATH_MODF_CALL_COUNT, \
      ISAAC_VITA_MATH_MODF_CALL_FNV64) \
    X(nextafterf, ISAAC_VITA_MATH_NEXTAFTERF_NAME, \
      ISAAC_VITA_MATH_NEXTAFTERF_IAT_RVA, \
      ISAAC_VITA_MATH_NEXTAFTERF_THUNK_RVA, \
      ISAAC_VITA_MATH_NEXTAFTERF_CALL_COUNT, \
      ISAAC_VITA_MATH_NEXTAFTERF_CALL_FNV64) \
    X(ciatan2, ISAAC_VITA_MATH_CIATAN2_NAME, \
      ISAAC_VITA_MATH_CIATAN2_IAT_RVA, ISAAC_VITA_MATH_CIATAN2_THUNK_RVA, \
      ISAAC_VITA_MATH_CIATAN2_CALL_COUNT, ISAAC_VITA_MATH_CIATAN2_CALL_FNV64) \
    X(asin, ISAAC_VITA_MATH_ASIN_NAME, ISAAC_VITA_MATH_ASIN_IAT_RVA, \
      ISAAC_VITA_MATH_ASIN_THUNK_RVA, ISAAC_VITA_MATH_ASIN_CALL_COUNT, \
      ISAAC_VITA_MATH_ASIN_CALL_FNV64) \
    X(atan, ISAAC_VITA_MATH_ATAN_NAME, ISAAC_VITA_MATH_ATAN_IAT_RVA, \
      ISAAC_VITA_MATH_ATAN_THUNK_RVA, ISAAC_VITA_MATH_ATAN_CALL_COUNT, \
      ISAAC_VITA_MATH_ATAN_CALL_FNV64) \
    X(setusermatherr, ISAAC_VITA_MATH_SETUSERMATHERR_NAME, \
      ISAAC_VITA_MATH_SETUSERMATHERR_IAT_RVA, \
      ISAAC_VITA_MATH_SETUSERMATHERR_THUNK_RVA, \
      ISAAC_VITA_MATH_SETUSERMATHERR_CALL_COUNT, \
      ISAAC_VITA_MATH_SETUSERMATHERR_CALL_FNV64) \
    X(log10, ISAAC_VITA_MATH_LOG10_NAME, ISAAC_VITA_MATH_LOG10_IAT_RVA, \
      ISAAC_VITA_MATH_LOG10_THUNK_RVA, ISAAC_VITA_MATH_LOG10_CALL_COUNT, \
      ISAAC_VITA_MATH_LOG10_CALL_FNV64) \
    X(cos, ISAAC_VITA_MATH_COS_NAME, ISAAC_VITA_MATH_COS_IAT_RVA, \
      ISAAC_VITA_MATH_COS_THUNK_RVA, ISAAC_VITA_MATH_COS_CALL_COUNT, \
      ISAAC_VITA_MATH_COS_CALL_FNV64) \
    X(exp, ISAAC_VITA_MATH_EXP_NAME, ISAAC_VITA_MATH_EXP_IAT_RVA, \
      ISAAC_VITA_MATH_EXP_THUNK_RVA, ISAAC_VITA_MATH_EXP_CALL_COUNT, \
      ISAAC_VITA_MATH_EXP_CALL_FNV64)

/* Kept as an empty compatibility hook for inventory users. */
#define ISAAC_VITA_MATH_LOUD_IMPORTS(X)

int isaac_vita_math_import(CPU *__restrict c, const char *name);
int isaac_vita_math_import_counted(CPU *__restrict c, const char *name,
                                   unsigned *call_count);

#endif
