#ifndef ISAAC_HOST_VITA_STARTUP_H
#define ISAAC_HOST_VITA_STARTUP_H

#include <stdint.h>

#include "guest.h"

/* Exact startup-platform imports and representative call sites from the
 * selected PE.  The ordinal constants describe the measured boot path after
 * the earlier clock/CRT/sync/memory/console frontier; they are call counts,
 * not unique-handler counts. */
#define ISAAC_VITA_STARTUP_ENV_NAME \
    "KERNEL32.dll!GetEnvironmentVariableA"
#define ISAAC_VITA_STARTUP_ENV_IAT_RVA       0x00606094U
#define ISAAC_VITA_STARTUP_ENV_IAT_VA        0x98606094U
#define ISAAC_VITA_STARTUP_ENV_CALL_RVA      0x005e3849U
#define ISAAC_VITA_STARTUP_ENV_RETURN_RVA    0x005e384fU
#define ISAAC_VITA_STARTUP_ENV_FALLBACK_CALL_RVA   0x005e38d9U
#define ISAAC_VITA_STARTUP_ENV_FALLBACK_RETURN_RVA 0x005e38dfU
#define ISAAC_VITA_STARTUP_ENV_FALLBACK_ABANDONED_NAME \
    "mimalloc_abandoned_page_reset"
#define ISAAC_VITA_STARTUP_ENV_FALLBACK_RESET_NAME \
    "mimalloc_reset_delay"
#define ISAAC_VITA_STARTUP_ENV_FALLBACK_ABANDONED_OPTION_RVA 0x007a9120U
#define ISAAC_VITA_STARTUP_ENV_FALLBACK_ABANDONED_NAME_RVA   0x006073ccU
#define ISAAC_VITA_STARTUP_ENV_FALLBACK_RESET_OPTION_RVA     0x007a915cU
#define ISAAC_VITA_STARTUP_ENV_FALLBACK_RESET_NAME_RVA       0x00607424U
#define ISAAC_VITA_STARTUP_ENV_NAME_MAX      64U
/* Exact capacity at both frozen-PE call sites, not a Vita policy limit. */
#define ISAAC_VITA_STARTUP_ENV_BUFFER_SIZE   65U
#define ISAAC_VITA_STARTUP_ENV_OPTION_FIRST_RVA 0x007a9030U
#define ISAAC_VITA_STARTUP_ENV_OPTION_LAST_RVA  0x007a9210U
#define ISAAC_VITA_STARTUP_ENV_OPTION_STRIDE     0x14U
#define ISAAC_VITA_STARTUP_ENV_PRIMARY_BOOT_CALL_COUNT 25U
#define ISAAC_VITA_STARTUP_ENV_FALLBACK_BOOT_CALL_COUNT 2U
#define ISAAC_VITA_STARTUP_ENV_FIRST_ORDINAL 27U
#define ISAAC_VITA_STARTUP_ENV_FALLBACK_ABANDONED_ORDINAL 40U
#define ISAAC_VITA_STARTUP_ENV_FALLBACK_RESET_ORDINAL 44U
#define ISAAC_VITA_STARTUP_ENV_LAST_ORDINAL  53U
#define ISAAC_VITA_STARTUP_ENV_BOOT_CALL_COUNT \
    (ISAAC_VITA_STARTUP_ENV_PRIMARY_BOOT_CALL_COUNT + \
     ISAAC_VITA_STARTUP_ENV_FALLBACK_BOOT_CALL_COUNT)

#define ISAAC_VITA_STARTUP_SYSTEM_INFO_NAME \
    "KERNEL32.dll!GetSystemInfo"
#define ISAAC_VITA_STARTUP_SYSTEM_INFO_IAT_RVA    0x006060a4U
#define ISAAC_VITA_STARTUP_SYSTEM_INFO_CALL_RVA   0x005e77e4U
#define ISAAC_VITA_STARTUP_SYSTEM_INFO_RETURN_RVA 0x005e77eaU
#define ISAAC_VITA_STARTUP_SYSTEM_INFO_ORDINAL    56U

/* 32-bit Windows SYSTEM_INFO layout exposed to the x86 guest.  The PE is
 * LARGE_ADDRESS_AWARE.  Three Vita user cores are available; the fourth mask
 * bit is SCE_KERNEL_CPU_MASK_SYSTEM and is deliberately not advertised. */
#define ISAAC_VITA_STARTUP_SYSTEM_INFO_SIZE        36U
#define ISAAC_VITA_STARTUP_PROCESSOR_ARCHITECTURE  0U
#define ISAAC_VITA_STARTUP_PAGE_SIZE               0x00001000U
#define ISAAC_VITA_STARTUP_MIN_APP_ADDRESS         0x00010000U
#define ISAAC_VITA_STARTUP_MAX_APP_ADDRESS         0xfffeffffU
#define ISAAC_VITA_STARTUP_ACTIVE_PROCESSOR_MASK   0x00000007U
#define ISAAC_VITA_STARTUP_PROCESSOR_COUNT         3U
#define ISAAC_VITA_STARTUP_PROCESSOR_TYPE          586U
#define ISAAC_VITA_STARTUP_ALLOCATION_GRANULARITY  0x00010000U
#define ISAAC_VITA_STARTUP_PROCESSOR_LEVEL         6U
#define ISAAC_VITA_STARTUP_PROCESSOR_REVISION      0U

#define ISAAC_VITA_STARTUP_LOAD_LIBRARY_NAME \
    "KERNEL32.dll!LoadLibraryA"
#define ISAAC_VITA_STARTUP_LOAD_LIBRARY_IAT_RVA 0x00606124U
#define ISAAC_VITA_STARTUP_LOAD_LIBRARY_NAME_MAX 32U

#define ISAAC_VITA_STARTUP_LOAD_KERNELBASE_CALL_RVA   0x005e7817U
#define ISAAC_VITA_STARTUP_LOAD_KERNELBASE_RETURN_RVA 0x005e781dU
#define ISAAC_VITA_STARTUP_LOAD_KERNELBASE_NAME_VA    0x98607bc8U
#define ISAAC_VITA_STARTUP_LOAD_KERNELBASE_ORDINAL    57U
#define ISAAC_VITA_STARTUP_LOAD_NTDLL_CALL_RVA        0x005e7855U
#define ISAAC_VITA_STARTUP_LOAD_NTDLL_RETURN_RVA      0x005e785bU
#define ISAAC_VITA_STARTUP_LOAD_NTDLL_NAME_VA         0x98607c00U
#define ISAAC_VITA_STARTUP_LOAD_NTDLL_ORDINAL         58U
#define ISAAC_VITA_STARTUP_LOAD_KERNEL32_CALL_RVA     0x005e7876U
#define ISAAC_VITA_STARTUP_LOAD_KERNEL32_RETURN_RVA   0x005e787cU
#define ISAAC_VITA_STARTUP_LOAD_KERNEL32_NAME_VA      0x98607c28U
#define ISAAC_VITA_STARTUP_LOAD_KERNEL32_ORDINAL      59U
#define ISAAC_VITA_STARTUP_LOAD_LIBRARY_BOOT_CALL_COUNT 3U

/* The save-path setup later probes USERENV dynamically.  Vita deliberately
 * reports the module absent; this is a measured fallback, not a synthetic
 * module handle. */
#define ISAAC_VITA_STARTUP_LOAD_USERENV_MODULE          "userenv"
#define ISAAC_VITA_STARTUP_LOAD_USERENV_CALL_RVA        0x0050a878U
#define ISAAC_VITA_STARTUP_LOAD_USERENV_RETURN_RVA      0x0050a87eU
#define ISAAC_VITA_STARTUP_LOAD_USERENV_NAME_RVA        0x0075a89cU
#define ISAAC_VITA_STARTUP_LOAD_USERENV_NAME_VA         0x9875a89cU
#define ISAAC_VITA_STARTUP_LOAD_USERENV_ORDINAL         269U

/* GLFW's optional desktop joystick setup probes winmm after preserving the
 * foreground-lock timeout.  The two preceding first-push vector grows each
 * execute malloc(4)+memmove(n=0), so the live winmm probe is attempt #526.
 * Vita has no native WinMM module; NULL is the measured, supported fallback
 * and prevents any synthetic FARPROC contract. */
#define ISAAC_VITA_STARTUP_LOAD_WINMM_MODULE             "winmm.dll"
#define ISAAC_VITA_STARTUP_LOAD_WINMM_NAME_RVA           0x0076707cU
#define ISAAC_VITA_STARTUP_LOAD_WINMM_NAME_VA            0x9876707cU
#define ISAAC_VITA_STARTUP_LOAD_WINMM_CALL_RVA           0x005a7479U
#define ISAAC_VITA_STARTUP_LOAD_WINMM_RETURN_RVA         0x005a747bU
#define ISAAC_VITA_STARTUP_LOAD_WINMM_ORDINAL            526U

#define ISAAC_VITA_STARTUP_FREE_LIBRARY_NAME \
    "KERNEL32.dll!FreeLibrary"
#define ISAAC_VITA_STARTUP_FREE_LIBRARY_IAT_RVA         0x00606104U
#define ISAAC_VITA_STARTUP_FREE_LIBRARY_IAT_VA          0x98606104U
#define ISAAC_VITA_STARTUP_FREE_USERENV_ARGUMENT_RVA    0x0050a911U
#define ISAAC_VITA_STARTUP_FREE_USERENV_CALL_RVA        0x0050a912U
#define ISAAC_VITA_STARTUP_FREE_USERENV_RETURN_RVA      0x0050a918U
#define ISAAC_VITA_STARTUP_FREE_USERENV_MODULE          0U
#define ISAAC_VITA_STARTUP_FREE_USERENV_ORDINAL         271U
#define ISAAC_VITA_STARTUP_USERENV_OWNED_CALL_COUNT     2U

/* Exact next unresolved import after the absent USERENV module/procedure path
 * and its measured empty-string memmove/vector allocation cleanup. */
#define ISAAC_VITA_STARTUP_USERENV_NEXT_NAME \
    "api-ms-win-crt-environment-l1-1-0.dll!getenv"
#define ISAAC_VITA_STARTUP_USERENV_NEXT_IAT_RVA         0x006064e4U
#define ISAAC_VITA_STARTUP_USERENV_NEXT_CALL_RVA        0x0050aa0bU
#define ISAAC_VITA_STARTUP_USERENV_NEXT_RETURN_RVA      0x0050aa0dU
#define ISAAC_VITA_STARTUP_USERENV_NEXT_ARGUMENT_VA     0x9875a9a8U
#define ISAAC_VITA_STARTUP_USERENV_NEXT_ARGUMENT        "USERPROFILE"
#define ISAAC_VITA_STARTUP_USERENV_NEXT_ATTEMPT_ORDINAL 274U

/* The Vita save root is supplied by platform.h.  These Win32 path seams all
 * translate guest paths into that one writable native root. */
#define ISAAC_VITA_STARTUP_PATH_MAX 1024U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTE_DIRECTORY 0x00000010U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTE_ARCHIVE   0x00000020U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTE_NORMAL    0x00000080U
#define ISAAC_VITA_STARTUP_INVALID_FILE_ATTRIBUTES  UINT32_MAX

/* Guest-thread-local compatibility values stored in CPU.  The numeric values
 * are the Win32 ERROR_* ABI. */
#define ISAAC_VITA_STARTUP_ERROR_SUCCESS             0U
#define ISAAC_VITA_STARTUP_ERROR_FILE_NOT_FOUND      2U
#define ISAAC_VITA_STARTUP_ERROR_PATH_NOT_FOUND      3U
#define ISAAC_VITA_STARTUP_ERROR_ACCESS_DENIED       5U
#define ISAAC_VITA_STARTUP_ERROR_INVALID_HANDLE      6U
#define ISAAC_VITA_STARTUP_ERROR_MOD_NOT_FOUND       126U
#define ISAAC_VITA_STARTUP_ERROR_ALREADY_EXISTS      183U
#define ISAAC_VITA_STARTUP_ERROR_ENVVAR_NOT_FOUND    203U

#define ISAAC_VITA_STARTUP_GET_LAST_ERROR_NAME \
    "KERNEL32.dll!GetLastError"
#define ISAAC_VITA_STARTUP_GET_LAST_ERROR_IAT_RVA    0x006060dcU
#define ISAAC_VITA_STARTUP_GET_LAST_ERROR_CALL_RVA   0x00567d92U
#define ISAAC_VITA_STARTUP_GET_LAST_ERROR_RETURN_RVA 0x00567d98U
#define ISAAC_VITA_STARTUP_GET_LAST_ERROR_FIRST_ORDINAL 2744U

#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_NAME \
    "KERNEL32.dll!GetFileAttributesA"
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_IAT_RVA 0x00606108U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_ROOT_CALL_RVA 0x0050aa33U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_ROOT_RETURN_RVA 0x0050aa35U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_ROOT_ORDINAL 276U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_SAVE_CALL_RVA 0x0050ae03U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_SAVE_RETURN_RVA 0x0050ae05U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_SAVE_ORDINAL 287U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_MODS_CALL_RVA 0x0050aef5U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_MODS_RETURN_RVA 0x0050aef7U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_MODS_ORDINAL 294U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_DATA_CALL_RVA 0x0050afa5U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_DATA_RETURN_RVA 0x0050afa7U
#define ISAAC_VITA_STARTUP_FILE_ATTRIBUTES_DATA_ORDINAL 298U

#define ISAAC_VITA_STARTUP_CREATE_DIRECTORY_NAME \
    "KERNEL32.dll!CreateDirectoryA"
#define ISAAC_VITA_STARTUP_CREATE_DIRECTORY_IAT_RVA 0x00606134U
#define ISAAC_VITA_STARTUP_CREATE_SAVE_CALL_RVA     0x0050ade7U
#define ISAAC_VITA_STARTUP_CREATE_SAVE_RETURN_RVA   0x0050ade9U
#define ISAAC_VITA_STARTUP_CREATE_SAVE_FIRST_ORDINAL 280U
#define ISAAC_VITA_STARTUP_CREATE_SAVE_LAST_ORDINAL 286U
#define ISAAC_VITA_STARTUP_CREATE_MODS_CALL_RVA     0x0050aee5U
#define ISAAC_VITA_STARTUP_CREATE_MODS_RETURN_RVA   0x0050aee7U
#define ISAAC_VITA_STARTUP_CREATE_MODS_ORDINAL      293U
#define ISAAC_VITA_STARTUP_CREATE_DATA_CALL_RVA     0x0050af95U
#define ISAAC_VITA_STARTUP_CREATE_DATA_RETURN_RVA   0x0050af97U
#define ISAAC_VITA_STARTUP_CREATE_DATA_ORDINAL      297U

#define ISAAC_VITA_STARTUP_CURRENT_DIRECTORY_NAME \
    "KERNEL32.dll!GetCurrentDirectoryA"
#define ISAAC_VITA_STARTUP_CURRENT_DIRECTORY_IAT_RVA 0x0060610cU
#define ISAAC_VITA_STARTUP_CURRENT_DIRECTORY_CALL_RVA 0x0050ae64U
#define ISAAC_VITA_STARTUP_CURRENT_DIRECTORY_RETURN_RVA 0x0050ae6aU
#define ISAAC_VITA_STARTUP_CURRENT_DIRECTORY_ORDINAL 288U

#define ISAAC_VITA_STARTUP_FULL_PATH_NAME \
    "KERNEL32.dll!GetFullPathNameW"
#define ISAAC_VITA_STARTUP_FULL_PATH_IAT_RVA        0x006060e8U
#define ISAAC_VITA_STARTUP_FULL_PATH_QUERY_CALL_RVA 0x00562facU
#define ISAAC_VITA_STARTUP_FULL_PATH_QUERY_RETURN_RVA 0x00562fb2U
#define ISAAC_VITA_STARTUP_FULL_PATH_QUERY_ORDINAL  343U
#define ISAAC_VITA_STARTUP_FULL_PATH_FILL_CALL_RVA  0x00562fedU
#define ISAAC_VITA_STARTUP_FULL_PATH_FILL_RETURN_RVA 0x00562ff3U
#define ISAAC_VITA_STARTUP_FULL_PATH_FILL_ORDINAL   345U
#define ISAAC_VITA_STARTUP_FULL_PATH_INPUT          "./"
#define ISAAC_VITA_STARTUP_FULL_PATH_ROOT_LENGTH    18U
#define ISAAC_VITA_STARTUP_FULL_PATH_REQUIRED       19U
#define ISAAC_VITA_STARTUP_FULL_PATH_ALLOCATION     0x36U
#define ISAAC_VITA_STARTUP_PATH_FIXED_CALL_COUNT    12U

#define ISAAC_VITA_STARTUP_PATH_NEXT_NAME \
    "KERNEL32.dll!FindFirstFileW"
#define ISAAC_VITA_STARTUP_PATH_NEXT_IAT_RVA        0x006060ecU
#define ISAAC_VITA_STARTUP_PATH_NEXT_CALL_RVA       0x00563036U
#define ISAAC_VITA_STARTUP_PATH_NEXT_RETURN_RVA     0x0056303cU
#define ISAAC_VITA_STARTUP_PATH_NEXT_ATTEMPT_ORDINAL 346U

/* GLFW temporarily sets SPI_SETFOREGROUNDLOCKTIMEOUT to zero around its
 * optional desktop initialization.  Attempts #524/#525 follow the two
 * malloc(4)+memmove(n=0) vector-growth pairs; #527 restores the saved value
 * after the absent-winmm fallback.  Model only this private process-local
 * state: never read or mutate a Vita/host desktop setting. */
#define ISAAC_VITA_STARTUP_SYSTEM_PARAMETERS_NAME \
    "USER32.dll!SystemParametersInfoA"
#define ISAAC_VITA_STARTUP_SYSTEM_PARAMETERS_IAT_RVA 0x006063fcU
#define ISAAC_VITA_STARTUP_SYSTEM_PARAMETERS_IAT_VA  0x986063fcU
#define ISAAC_VITA_STARTUP_SPI_GET_FOREGROUND_LOCK_TIMEOUT 0x00002000U
#define ISAAC_VITA_STARTUP_SPI_SET_FOREGROUND_LOCK_TIMEOUT 0x00002001U
#define ISAAC_VITA_STARTUP_SPI_UPDATE_FLAGS_NONE      0U
#define ISAAC_VITA_STARTUP_SPI_UPDATE_FLAGS_SEND_CHANGE 2U
#define ISAAC_VITA_STARTUP_SPI_SAVED_TIMEOUT_RVA      0x007fe364U
#define ISAAC_VITA_STARTUP_SPI_SAVED_TIMEOUT_VA       0x987fe364U
#define ISAAC_VITA_STARTUP_SPI_GET_CALL_RVA           0x005a745fU
#define ISAAC_VITA_STARTUP_SPI_GET_RETURN_RVA         0x005a7461U
#define ISAAC_VITA_STARTUP_SPI_GET_ORDINAL            524U
#define ISAAC_VITA_STARTUP_SPI_SET_ZERO_CALL_RVA      0x005a746cU
#define ISAAC_VITA_STARTUP_SPI_SET_ZERO_RETURN_RVA    0x005a746eU
#define ISAAC_VITA_STARTUP_SPI_SET_ZERO_VALUE         0U
#define ISAAC_VITA_STARTUP_SPI_SET_ZERO_ORDINAL       525U
#define ISAAC_VITA_STARTUP_SPI_RESTORE_CALL_RVA       0x005a7647U
#define ISAAC_VITA_STARTUP_SPI_RESTORE_RETURN_RVA     0x005a764dU
#define ISAAC_VITA_STARTUP_SPI_RESTORE_ORDINAL        527U
#define ISAAC_VITA_STARTUP_SPI_MEASURED_CALL_COUNT    3U
#define ISAAC_VITA_STARTUP_LATE_DESKTOP_CALL_COUNT    4U

#define ISAAC_VITA_STARTUP_QPF_NAME \
    "KERNEL32.dll!QueryPerformanceFrequency"
#define ISAAC_VITA_STARTUP_QPF_IAT_RVA       0x006060c8U
#define ISAAC_VITA_STARTUP_QPF_CALL_RVA      0x005e9aafU
#define ISAAC_VITA_STARTUP_QPF_RETURN_RVA    0x005e9ab5U
#define ISAAC_VITA_STARTUP_QPF_FREQUENCY     1000000U
#define ISAAC_VITA_STARTUP_QPF_ORDINAL       64U
#define ISAAC_VITA_STARTUP_NEXT_INITTERM_ORDINAL 67U

#define ISAAC_VITA_STARTUP_NEXT_NAME \
    "KERNEL32.dll!SetUnhandledExceptionFilter"
#define ISAAC_VITA_STARTUP_NEXT_IAT_RVA     0x0060603cU
#define ISAAC_VITA_STARTUP_NEXT_CALL_RVA    0x005ebf7dU
#define ISAAC_VITA_STARTUP_NEXT_RETURN_RVA  0x005ebf83U
#define ISAAC_VITA_STARTUP_NEXT_CALLBACK_VA 0x985ebf84U
#define ISAAC_VITA_STARTUP_NEXT_ATTEMPT_ORDINAL 68U

#define ISAAC_VITA_STARTUP_IMPORT_COUNT 11U
#define ISAAC_VITA_STARTUP_BOOT_CALL_COUNT \
    (ISAAC_VITA_STARTUP_ENV_BOOT_CALL_COUNT + 1U + \
     ISAAC_VITA_STARTUP_LOAD_LIBRARY_BOOT_CALL_COUNT + 1U)

/* Map a narrow guest path to the canonical native Vita writable root.
 * Relative paths and either accepted root spelling stay confined below it. */
int isaac_vita_startup_map_path(CPU *__restrict c, uint32_t guest_path,
                                char *native_path, uint32_t capacity);

/* Returns one only for the ten exact import names above.  A rejected name is
 * a mutation-free handoff to the outer Vita dispatcher. */
int isaac_vita_startup_import(CPU *__restrict c, const char *name);

/* A recognized import increments CALL_COUNT before entering its handler so a
 * range or policy fault remains counted after guest_fault unwinds. */
int isaac_vita_startup_import_counted(CPU *__restrict c, const char *name,
                                      unsigned *call_count);

#endif
