#ifndef ISAAC_HOST_VITA_FILESYSTEM_H
#define ISAAC_HOST_VITA_FILESYSTEM_H

#include <stdint.h>

#include "guest.h"

/* Complete api-ms-win-crt-filesystem-l1-1-0 import block in the frozen
 * 8,650,240-byte Repentance PE.  Physical-call counts are static sites, not
 * runtime occurrences. */
#define ISAAC_VITA_FILESYSTEM_DLL_NAME \
    "api-ms-win-crt-filesystem-l1-1-0.dll"
#define ISAAC_VITA_FILESYSTEM_FIRST_IAT_RVA 0x006064ecU
#define ISAAC_VITA_FILESYSTEM_LAST_IAT_RVA  0x006064f0U
#define ISAAC_VITA_FILESYSTEM_IMPORT_COUNT  2U
#define ISAAC_VITA_FILESYSTEM_PHYSICAL_CALL_COUNT 9U

#define ISAAC_VITA_FILESYSTEM_REMOVE_NAME \
    "api-ms-win-crt-filesystem-l1-1-0.dll!remove"
#define ISAAC_VITA_FILESYSTEM_REMOVE_IAT_RVA 0x006064ecU
#define ISAAC_VITA_FILESYSTEM_REMOVE_CALL_COUNT 8U
#define ISAAC_VITA_FILESYSTEM_REMOVE_CALL_FNV64 \
    UINT64_C(0x7450e89437d00438)

/* owner RVA, absolute-IAT call RVA, return RVA */
#define ISAAC_VITA_FILESYSTEM_REMOVE_CALLS(X) \
    X(0x0025e3b0U, 0x0025e5daU, 0x0025e5e0U) \
    X(0x0025f240U, 0x0025f2c7U, 0x0025f2cdU) \
    X(0x0040e150U, 0x0040e357U, 0x0040e35dU) \
    X(0x00469d40U, 0x00469f39U, 0x00469f3fU) \
    X(0x00474ad0U, 0x0047531bU, 0x00475321U) \
    X(0x00520ac0U, 0x00520b6bU, 0x00520b71U) \
    X(0x00520b80U, 0x00520c22U, 0x00520c28U) \
    X(0x00567cc0U, 0x00567cc6U, 0x00567cccU)

#define ISAAC_VITA_FILESYSTEM_ACCESS_NAME \
    "api-ms-win-crt-filesystem-l1-1-0.dll!_access"
#define ISAAC_VITA_FILESYSTEM_ACCESS_IAT_RVA 0x006064f0U
#define ISAAC_VITA_FILESYSTEM_ACCESS_OWNER_RVA  0x00596320U
#define ISAAC_VITA_FILESYSTEM_ACCESS_CALL_RVA   0x00596340U
#define ISAAC_VITA_FILESYSTEM_ACCESS_RETURN_RVA 0x00596346U
#define ISAAC_VITA_FILESYSTEM_ACCESS_CALL_COUNT 1U
#define ISAAC_VITA_FILESYSTEM_ACCESS_CALL_FNV64 \
    UINT64_C(0x7223dd96f4295075)

/* The sole physical _access caller pushes mode zero.  The standard UCRT modes
 * are nevertheless exact and map directly onto Vita newlib's existence/
 * read-only checks. */
#define ISAAC_VITA_FILESYSTEM_ACCESS_EXISTS 0U
#define ISAAC_VITA_FILESYSTEM_ACCESS_WRITE  2U
#define ISAAC_VITA_FILESYSTEM_ACCESS_READ   4U
#define ISAAC_VITA_FILESYSTEM_ACCESS_RW     6U
#define ISAAC_VITA_FILESYSTEM_ACCESS_MODE_MASK 6U

/* Current live frontier.  sub_25e3b0 constructs its stack buffer with
 * sprintf_s("%s%s", USERPROFILE + "/", "cmd_history.txt").  Vita getenv
 * exposes the guest title root, so the exact guest/native values below follow
 * without guessing a runtime pointer. */
#define ISAAC_VITA_FILESYSTEM_CURRENT_OWNER_RVA  0x0025e3b0U
#define ISAAC_VITA_FILESYSTEM_CURRENT_CALL_RVA   0x0025e5daU
#define ISAAC_VITA_FILESYSTEM_CURRENT_RETURN_RVA 0x0025e5e0U
#define ISAAC_VITA_FILESYSTEM_CURRENT_BUILD_CALL_RVA   0x0025e412U
#define ISAAC_VITA_FILESYSTEM_CURRENT_BUILD_RETURN_RVA 0x0025e417U
#define ISAAC_VITA_FILESYSTEM_CURRENT_FORMAT_RVA 0x00742af8U
#define ISAAC_VITA_FILESYSTEM_CURRENT_FORMAT "%s%s"
#define ISAAC_VITA_FILESYSTEM_CURRENT_SUFFIX_RVA 0x00747470U
#define ISAAC_VITA_FILESYSTEM_CURRENT_SUFFIX "cmd_history.txt"
#define ISAAC_VITA_FILESYSTEM_CURRENT_BUFFER_CAPACITY 0x100U
#define ISAAC_VITA_FILESYSTEM_USERPROFILE_BUFFER_VA 0x987fd690U
#define ISAAC_VITA_FILESYSTEM_USERPROFILE_NAME_RVA 0x0075a9a8U
#define ISAAC_VITA_FILESYSTEM_USERPROFILE_NAME "USERPROFILE"
#define ISAAC_VITA_FILESYSTEM_USERPROFILE_FORMAT_RVA 0x0075a9a4U
#define ISAAC_VITA_FILESYSTEM_USERPROFILE_FORMAT "%s/"
#define ISAAC_VITA_FILESYSTEM_USERPROFILE_GETENV_CALL_RVA 0x0050aa0bU
#define ISAAC_VITA_FILESYSTEM_USERPROFILE_GETENV_RETURN_RVA 0x0050aa0dU
#define ISAAC_VITA_FILESYSTEM_CURRENT_GUEST_PATH \
    "ux0:data/isaacr001/cmd_history.txt"
#define ISAAC_VITA_FILESYSTEM_CURRENT_NATIVE_PATH \
    "ux0:/data/isaacr001/cmd_history.txt"
#define ISAAC_VITA_FILESYSTEM_CURRENT_IMPORT_ORDINAL 11180950U
#define ISAAC_VITA_FILESYSTEM_CURRENT_DYNAMIC_COUNT 8861U

#define ISAAC_VITA_FILESYSTEM_IMPORTS(X) \
    X(remove, ISAAC_VITA_FILESYSTEM_REMOVE_NAME, \
      ISAAC_VITA_FILESYSTEM_REMOVE_IAT_RVA, \
      ISAAC_VITA_FILESYSTEM_REMOVE_CALL_COUNT, \
      ISAAC_VITA_FILESYSTEM_REMOVE_CALL_FNV64) \
    X(access, ISAAC_VITA_FILESYSTEM_ACCESS_NAME, \
      ISAAC_VITA_FILESYSTEM_ACCESS_IAT_RVA, \
      ISAAC_VITA_FILESYSTEM_ACCESS_CALL_COUNT, \
      ISAAC_VITA_FILESYSTEM_ACCESS_CALL_FNV64)

int isaac_vita_filesystem_import(CPU *__restrict c, const char *name);
int isaac_vita_filesystem_import_counted(CPU *__restrict c, const char *name,
                                         unsigned *call_count);

#endif
